# -*- coding: utf-8 -*-
"""Project_Code3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vJBuMzL8mUg5WGnqvWpllUiG9dYZrWhM

Convolution
"""

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
import numpy as np



"""This is Just a Demo !"""



"""For Full Project, Mail me at vatshayan007@gmail.com Now"""

