# -*- coding: utf-8 -*-
"""Project_code2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y2AoVaFeHQepmQsbJMo6CJyqGdPU0jHE

GAN
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
import random
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline



"""For Full Project, Mail me at (vatshayan007@gmail.com) Now"""